import {request} from "./Methods";
import {URLTypes} from "./URLTypes";

export const signIn = async (params) => await request(URLTypes.SIGN_IN, params, 'post');
export const findPartner = async (params) => await request(URLTypes.FIND_PARTNER, params, 'get');
export const findPartnerQuery = async (params) => await request(URLTypes.GET_ALL_PARTNERS, params, 'get');
export const tryFindPartner = async (params) => await request(URLTypes.TRY_FIND_PARTNER, params, 'get');
export const registerConfirmPhone = async (params) => await request(URLTypes.REGISTER_CONFIRM_PHONE, params, 'post');
export const registerSendConfirmPhone = async (params) => await request(URLTypes.REGISTER_SEND_CONFIRM_PHONE, params, 'post');
export const registerPartner = async (params, config) => await request(URLTypes.REGISTER_PARTNER, params, 'post', config);
export const forgotPassword = async (params) => await request(URLTypes.FORGOT_PASSWORD, params, 'post');
export const validatePartner = async (params) => await request(URLTypes.VALIDATE_PARTNER, params, 'get');
export const getGuests = async (params) => await request(URLTypes.GET_GUESTS, params, 'get');
export const generateGuestsQR = async (params, queryStringParams = []) => await request(URLTypes.GENERATE_GUEST_QR, params, 'post', null, queryStringParams);
export const getCategories = async (params) => await request(URLTypes.GET_CATEGORIES, params, 'get');
export const getCategoriesDetail = async (params) => await request(URLTypes.GET_CATEGORIES_DETAIL, params, 'get');
export const getCategoryDetail = async (params) => await request(URLTypes.GET_CATEGORY_DETAIL, params, 'get');
export const getAllServices = async (params) => await request(URLTypes.GET_ALL_SERVICES, params, 'get');
export const getIntervalsTime = async (params, queryStringParams = []) => await request(URLTypes.GET_INTERVALS, params, 'get', null, queryStringParams);
export const cacheBookHour = async (params, queryStringParams = []) => await request(URLTypes.CACHE_BOOKING, params, 'post', null, queryStringParams);
export const bookService = async (params, queryStringParams = []) => await request(URLTypes.BOOK_SERVICE, params, 'post', null, queryStringParams);
export const getAllBookings = async (params) => await request(URLTypes.GET_ALL_BOOKINGS, params, 'get');
export const getAllInvitations = async (params) => await request(URLTypes.GET_ALL_INVITATIONS, params, 'get');
export const getProfile = async (params, queryStringParams = []) => await request(URLTypes.GET_PROFILE, params, 'get', null, queryStringParams);
export const getAdditionalMembers = async (params) => await request(URLTypes.GET_ADDITIONAL_MEMBERS, params, 'get');
export const getPoints = async (params, queryStringParams = []) => await request(URLTypes.GET_POINTS, params, 'get', null, queryStringParams);
export const setReservationStatus = async (params, queryStringParams = []) => await request(URLTypes.SET_RESERVATION_STATUS, params, 'put', null, queryStringParams);